### PR TITLE
PR for GH-628

### PR DESCRIPTION
**Pull request by crapo**
This fixes a number of gaps and issues in the handling of union and intersection classes and typed lists of union and intersection classes. Although I've added a significant number of JUnit test cases, all of which pass, I'm sure that there are many possible scenarios that are not yet covered by test cases. For that reason, I'd be much more comfortable if @agabaldon and @AbhaMoitra  were to pull the update zip associated with this PR from github (from installation instructions--"Note: to install the latest bleeding edge automated build, go to Actions, click on the latest (or any desired) result, scroll down to Artifacts, and download the ZIP file for installation.") and exercise it a bit in normal use before merging into development. Please inform me of any issues found by adding to issue #628 .

### CODE REVIEW

**Comment by tuxji** [comment]
@agabaldon and/or @AbhaMoitra, I'm waiting for you to test the built artifact at least a little bit before I review and merge the PR.

**Comment by AbhaMoitra** [comment]
@agabaldon : can you do the testing, I am pre-occupied with a number of other things at the moment.

**Comment by agabaldon** [comment]
I tried to install the update in Eclipse-2020-12 where I had a previous version of the SADL plugin and got this error when Eclipse restarted. Did you install as an update or on a fresh Eclipse install?

Screen Shot 2021-03-17 at 3 24 20 PM

**Comment by crapo** [comment]
@agabaldon , I think I installed as an update in Eclipse 2020-12. I've never seen this error. @tuxji , do you have any ideas?

**Comment by tuxji** [comment]
I haven't seen this error either.  I successfully installed the [zip file](https://github.com/SemanticApplicationDesignLanguage/sadl/suites/2280519374/artifacts/47663882) from GitHub's most recent Actions run into two Eclipse DSL instances without any problems.  The first DSL instance was an existing DSL instance with an existing SADL feature I'd originally installed when it was Eclipse DSL 2020-03 and then updated it to 2020-06, 2020-09, 2020-12, and 2021-03 over time.  The second DSL instance was a freshly unpacked DSL 2020-12 instance without any changes made to it.  Both were on Ubuntu 20.04 under WSL2.  I was able to run Test Model on VERDICT's Run.sadl file successfully in the first DSL instance after updating SADL, so that part works too.

**Review by tuxji — APPROVED** [review]
+1

**Comment by agabaldon** [comment]
I guess we are not testing then.

**Comment by agabaldon** [comment]
This update is not working for me. 
I got the same error trying to install on a fresh Eclipse 2020-12. 
I also tried 2021-03 for Java and the installation of SADL cannot be completed because:

"Cannot complete the install because of a conflicting dependency.
  Software being installed: SADL Feature 3.5.0.202103171550 (com.ge.research.sadl.feature.feature.group 3.5.0.202103171550)
  Only one of the following can be installed at once: 
    Xtext 2.25.0.v20210301-0843 (org.eclipse.xtext 2.25.0.v20210301-0843)
    Xtext 2.23.0.v20200831-0730 (org.eclipse.xtext 2.23.0.v20200831-0730)
  Cannot satisfy dependency:
    From: SADL Feature 3.5.0.202103171550 (com.ge.research.sadl.feature.feature.group 3.5.0.202103171550)
    To: org.eclipse.equinox.p2.iu; com.ge.research.sadl.xtextgenerator [3.5.0.202103171550,3.5.0.202103171550]
  Cannot satisfy dependency:
    From: SADL Feature 3.5.0.202103171550 (com.ge.research.sadl.feature.feature.group 3.5.0.202103171550)
    To: org.eclipse.equinox.p2.iu; org.eclipse.xtext.runtime.feature.group [2.23.0.v20200831-0926,2.23.0.v20200831-0926]
  Cannot satisfy dependency:
    From: Xtextgenerator 3.5.0.202103171550 (com.ge.research.sadl.xtextgenerator 3.5.0.202103171550)
    To: osgi.bundle; org.eclipse.emf.mwe2.launch 0.0.0
  Cannot satisfy dependency:
    From: MWE2 Language 2.12.1.v20210218-2134 (org.eclipse.emf.mwe2.language 2.12.1.v20210218-2134)
    To: osgi.bundle; org.eclipse.xtext 2.25.0
  Cannot satisfy dependency:
    From: MWE2 Launch 2.12.1.v20210218-2134 (org.eclipse.emf.mwe2.launch 2.12.1.v20210218-2134)
    To: osgi.bundle; org.eclipse.emf.mwe2.language 0.0.0
  Cannot satisfy dependency:
    From: Xtext Runtime 2.23.0.v20200831-0926 (org.eclipse.xtext.runtime.feature.group 2.23.0.v20200831-0926)
    To: org.eclipse.equinox.p2.iu; org.eclipse.xtext [2.23.0.v20200831-0730,2.23.0.v20200831-0730]"

**Comment by tuxji** [comment]
I merged the PR because I've been working on SADL the last few days myself and I didn't want my changes to cause a conflict making the PR unmergeable.  I've changed the Maven compiler settings from Java 8 to Java 11, updated the versions of dependencies and plugins in the poms, fixed the resulting SADL compilation problems, and made fixes for other problems I encountered.  I also changed the directory structure more to my liking but I will stage the pom and code changes in a PR first and propose the directory changes for discussion later.  I will need a few hours to stage my pom and code changes separately and I plan to work on another project today.  If you can wait until next week, you can try a new install with my changes to see if your installation problems go away.

**Comment by agabaldon** [comment]
I tried Eclipses 2020-03, 2020-09, 2020-12, 2021-03 for Java, and none of them work with the new plugin. I even tried wiping out the .p2 directory. 

In case the problem had something to do with using the Eclipse Installer app, I downloaded Eclipse Java 2020-12 installer. When I tried to install SADL, I got:

Cannot complete the install because one or more required items could not be found.
  Software being installed: SADL Feature 3.5.0.202103211612 (com.ge.research.sadl.feature.feature.group 3.5.0.202103211612)
  Missing requirement: com.ge.research.sadl 3.5.0.202103211612 (com.ge.research.sadl 3.5.0.202103211612) requires 'osgi.bundle; org.eclipse.xtend.lib 2.14.0' but it could not be found
  Cannot satisfy dependency:
    From: SADL Feature 3.5.0.202103211612 (com.ge.research.sadl.feature.feature.group 3.5.0.202103211612)
    To: org.eclipse.equinox.p2.iu; com.ge.research.sadl [3.5.0.202103211612,3.5.0.202103211612]

**Comment by agabaldon** [comment]
I'm out of ideas. I think I'm going to need help from @kittaakos

**Comment by tuxji** [comment]
@agabaldon I've opened PR #636 with my changes to move SADL completely to Java 11 and make it work in Eclipse 2020-12.  The checks have passed and CI has built the zip file.  Please download the zip file from the [run](https://github.com/SemanticApplicationDesignLanguage/sadl/actions/runs/681563113) and try it in your Eclipse 2020-12 instance.

**Comment by gSeaVelo** [comment]
Note that 

> This update is not working for me.
> I got the same error trying to install on a fresh Eclipse 2020-12.
> I also tried 2021-03 for Java and the installation of SADL cannot be completed because:
> 
> "Cannot complete the install because of a conflicting dependency.
> Software being installed: SADL Feature 3.5.0.202103171550 (com.ge.research.sadl.feature.feature.group 3.5.0.202103171550)
> Only one of the following can be installed at once:
> Xtext 2.25.0.v20210301-0843 (org.eclipse.xtext 2.25.0.v20210301-0843)
> Xtext 2.23.0.v20200831-0730 (org.eclipse.xtext 2.23.0.v20200831-0730)
> Cannot satisfy dependency:
> From: SADL Feature 3.5.0.202103171550 (com.ge.research.sadl.feature.feature.group 3.5.0.202103171550)
> To: org.eclipse.equinox.p2.iu; com.ge.research.sadl.xtextgenerator [3.5.0.202103171550,3.5.0.202103171550]
> Cannot satisfy dependency:
> From: SADL Feature 3.5.0.202103171550 (com.ge.research.sadl.feature.feature.group 3.5.0.202103171550)
> To: org.eclipse.equinox.p2.iu; org.eclipse.xtext.runtime.feature.group [2.23.0.v20200831-0926,2.23.0.v20200831-0926]
> Cannot satisfy dependency:
> From: Xtextgenerator 3.5.0.202103171550 (com.ge.research.sadl.xtextgenerator 3.5.0.202103171550)
> To: osgi.bundle; org.eclipse.emf.mwe2.launch 0.0.0
> Cannot satisfy dependency:
> From: MWE2 Language 2.12.1.v20210218-2134 (org.eclipse.emf.mwe2.language 2.12.1.v20210218-2134)
> To: osgi.bundle; org.eclipse.xtext 2.25.0
> Cannot satisfy dependency:
> From: MWE2 Launch 2.12.1.v20210218-2134 (org.eclipse.emf.mwe2.launch 2.12.1.v20210218-2134)
> To: osgi.bundle; org.eclipse.emf.mwe2.language 0.0.0
> Cannot satisfy dependency:
> From: Xtext Runtime 2.23.0.v20200831-0926 (org.eclipse.xtext.runtime.feature.group 2.23.0.v20200831-0926)
> To: org.eclipse.equinox.p2.iu; org.eclipse.xtext [2.23.0.v20200831-0730,2.23.0.v20200831-0730]"

Note that you can get around this error by installing xtext version 2.23 first, and then installing the current release (SADL Version 3.5.0 build 20201224).

**Pull request merged**
