### PR TITLE
3.3 - after demo

### PR DESCRIPTION
**Pull request by kittaakos**

### CODE REVIEW

**Comment by crapo** [comment]
@kittaakos , does this merge MissingPatterns into development? I can't currently build MissingPatterns. Should I switch to this branch and if it works well merge PR and build develoment?

**Comment by kittaakos** [comment]
> does this merge MissingPatterns into development?

Yes. Technically, it won't merge `MissingPatterns` into `development`, but this branch contains all changes from `MissingPattern`.

> Should I switch to this branch and if it works well merge PR and build develoment?

Yes, please.

----

The Eclipse version that we have to use from now on is:
```
Eclipse DSL Tools

Version: 2020-03 (4.15.0)
Build id: 20200313-1211
```

----
Verification of the SADL p2 update against Eclipse DSL Tools 2020-03 (4.15.0):

Screen Shot 2020-04-29 at 13 47 40
Screen Shot 2020-04-29 at 13 47 52

Screen Shot 2020-04-29 at 13 48 31

Screen Shot 2020-04-29 at 13 48 47

Screen Shot 2020-04-29 at 13 48 59

Screen Shot 2020-04-29 at 13 50 16

**Comment by crapo** [comment]
@kittaakos , I've successfully created a new workspace with this 3.3-after-demo branch. Maven build passes all tests. It appears to work well. I think I should merge into development. Sound OK?

**Comment by kittaakos** [comment]
> Sound OK?

I think so 👍

**Pull request merged**
