### PR TITLE
Web SADL - SemTK

### PR DESCRIPTION
**Pull request by kittaakos**

### CODE REVIEW

**Comment by kittaakos** [comment]
@crapo, as you are the owner of the AppVeyor project: you can delete it once this PR is merged. We will use Travis CI to run the Windows build too. Thank you!

> you can delete it

Steps how to delete it:
 - Go to https://ci.appveyor.com/projects,
 - Select the project (`sadlos2`),
 - On the left, select `Delete Project`, 
 - Delete it.

**Comment by kittaakos** [comment]
> @crapo, as you are the owner of the AppVeyor project: you can delete it once this PR is merged. We will use Travis CI to run the Windows build too. Thank you!
> 
> > you can delete it
> 
> Steps how to delete it:
> 
> * Go to https://ci.appveyor.com/projects,
> * Select the project (`sadlos2`),
> * On the left, select `Delete Project`,
> * Delete it.

Please ignore this. The Java support is [limited currently](https://travis-ci.community/t/java-support-on-windows/286) on Windows. I had to keep the AppVeyor build.

**Comment by kittaakos** [comment]
This PR is ready for the review. Unfortunately, for some reason, we (the  CI) have been [rate-limited](https://travis-ci.org/crapo/sadlos2/jobs/651461730#L268), hence the Docker publishing phase has failed. I am looking into it.

**Comment by kittaakos** [comment]
> have been [rate-limited](https://travis-ci.org/crapo/sadlos2/jobs/651461730#L268),

Seems to be a bug with `npm/cli`: https://github.com/npm/cli/issues/836

**Comment by kittaakos** [comment]
Update: https://status.npmjs.org/incidents/5qxhhcx0vtlc

**Comment by kittaakos** [comment]
I have quickly rebased the PR from the `development` branch, checked out the source on my Windows machine and built both the language server and the Theia app; it worked.

Hopefully, the NPM issue has been resolved too, and we can merge the changes once the review is done. 🤞

**Review by crapo — APPROVED** [review]
I don't know enough to comment on most of these changes :-) So, looks good to me.

**Comment by kittaakos** [comment]
@tuxji, do you happen to have time to look into the Maven, Gradle related changes. In a nutshell, the PR contains the following modifications:
 - Xtext 2.20.0,
 - LSP4J 0.8.1,
 - Theia 0.16.x,
 - Build the LS with Maven,
 - Got rid of the Gradle build,
 - Updated the target platform for Eclipse. (No Eclipse SDK version changes were required.)

I also removed the pinned dependencies of the `xtend-maven-plugin`; they're not needed anymore. 

To be able to build from the source, one has to run `mvn clean && mvn verify`. The LS should be under `com.ge.research.sadl.ide/target/languageserver` (inside the `sadl3` folder).

Thank you!

**Review by tuxji — APPROVED** [review]
Hi Akos, I just got back from a trip.  I've reviewed the diffs and they look good.  I've built the branch locally and the build output looks good too.  I approve merging web-sadl-semtk into development; it will upgrade SADL's dependencies and make its build more modern.  Thank you!

**Comment by kittaakos** [comment]
> I approve merging web-sadl-semtk into development

Thank you for the review, John!

**Pull request merged**
