### PR TITLE
Fixed the NPM publishing.

### PR DESCRIPTION
**Pull request by kittaakos**
- Moved the extension under 'packages'.
 - Moved the app under 'apps'.
 - Merged the .gitignore files.
 - Aligned the relative paths.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

-----
Npmjs publishing works with my credentials. e.g: https://www.npmjs.com/package/sadl-extension/v/0.2.0-next.c3dd572b

### CODE REVIEW

**Review by tuxji — APPROVED** [review]
Thank you!  Will merge and check CI now.

**Comment by kittaakos** [comment]
> check CI now.

Ping me if the issue still persists, or something is wrong with the Docker part.

**Comment by tuxji** [comment]
The Docker part works after fixing the yarn.lock path!  

I noticed that the workflow appears to build two Docker images.  Both the Build WebSADL Docker image and the Publish WebSADL Docker image steps print Docker build image output.  Are they building the same image twice or are they building two different images?  If two different images, what is the reason for building two images and then publishing the second image?

**Comment by kittaakos** [comment]
> I noticed that the workflow appears to build two Docker images.

Good point. This is just a guess but I think `elgohr/Publish-Docker-Github-Action` action has a side-effect, and it builds the Docker image once more before publishing. We do not need it. Instead of using the action, maybe we can try to just do the publishing manually with something like this (I have not tried it):
```
run: |
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker push theiaide/sadl
```

Also, once the CI is back, we should update the build-badges in the main README and get rid of the Travis and AppVeyor links and use the build-badge from GH Actions.

**Comment by kittaakos** [comment]
> maybe we can try to just do the publishing manually with something like this (I have not tried it):

Based on the old steps:

https://github.com/SemanticApplicationDesignLanguage/sadl/blob/fa7612d1209827aab36b5a87388dd6ba9c39cfdc/.travis.yml#L63

https://github.com/SemanticApplicationDesignLanguage/sadl/blob/fa7612d1209827aab36b5a87388dd6ba9c39cfdc/.travis.yml#L66

I hope this helps.

**Pull request merged**
